<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Tunnela.Desktop</AssemblyName>
    <Product>Tunnela</Product>
    <Title>Tunnela</Title>
    <AssemblyTitle>Tunnela</AssemblyTitle>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Tunnela.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../LICENSE" Link="licenses/TUNNELA_LICENSE.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <InternalsVisibleTo Include="Tunnela.Desktop.Tests" />
    <Resource Include="Assets\Tunnela.ico" />
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
    <ProjectReference Include="..\Tunnela.Contracts\Tunnela.Contracts.csproj" />
    <ProjectReference Include="..\Tunnela.Core\Tunnela.Core.csproj" />
  </ItemGroup>
</Project>
